site_name: Engin's Personal Docs
theme:
  name: material
  palette:
  - scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/owl-head.png
  favicon: img/owl-head.png
  language: en
repo_name: EnginEken
repo_url: https://github.com/EnginEken/
plugins:
- search
markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
nav:
- Home: index.md
- About: about.md
- Markdown Tips: mrkdwn.md
- Training:
  - Go Training: 
    - Basics: GoTraining/basics.md
- HowTo:
  - Create-Update-Comment Jira Ticet: HowTo/create-update-comment-jira.md
  - Automating Global Protect VPN Connection: HowTo/automate-vpn.md
  - How to Install Smokeping: HowTo/install-smokeping.md
extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- js/termynal.js
- js/custom.js
